from views.login import render_login
from views.sidebar import render_sidebar
from views.header import render_header
from views.admin import render_admin
from views.submit import render_submit
from views.trade import render_trade
from views.reveal import render_reveal
from views.leaderboard import render_leaderboard
from views.game_over import render_game_over
